///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define BONCOMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "52B5ADE8-5572-4D32-B389-552CA6A1D367"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (PatternProcessor)"
#define COCLASS_UUID "DF327162-DA68-4CD7-8AEB-BBECA1A65A4E"
#define COCLASS_NAME "MGA Interpreter CoClass (PatternProcessor)"
#define COCLASS_PROGID "MGA.Interpreter.PatternProcessor"

#define COCLASS_UUID_EXPLODED1  0xdf327162
#define COCLASS_UUID_EXPLODED2   0xda68
#define COCLASS_UUID_EXPLODED3   0x4cd7
#define COCLASS_UUID_EXPLODED4   0x8a
#define COCLASS_UUID_EXPLODED5   0xeb
#define COCLASS_UUID_EXPLODED6   0xbb
#define COCLASS_UUID_EXPLODED7   0xec
#define COCLASS_UUID_EXPLODED8   0xa1
#define COCLASS_UUID_EXPLODED9   0xa6
#define COCLASS_UUID_EXPLODED10  0x5a
#define COCLASS_UUID_EXPLODED11  0x4e


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "PatternProcessor"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "PatternProcessor"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGM_INDEPENDENT


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
