///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define BON2COMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "9EB1F214-EFE1-4B6D-BDA9-7BCD498F2E2C"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (BONExtender)"
#define COCLASS_UUID "EE00B878-7208-44AB-8106-1A8320C019A3"
#define COCLASS_NAME "MGA Interpreter CoClass (BONExtender)"
#define COCLASS_PROGID "MGA.Interpreter.BONExtender"

#define COCLASS_UUID_EXPLODED1  0xee00b878
#define COCLASS_UUID_EXPLODED2   0x7208
#define COCLASS_UUID_EXPLODED3   0x44ab
#define COCLASS_UUID_EXPLODED4   0x81
#define COCLASS_UUID_EXPLODED5   0x6
#define COCLASS_UUID_EXPLODED6   0x1a
#define COCLASS_UUID_EXPLODED7   0x83
#define COCLASS_UUID_EXPLODED8   0x20
#define COCLASS_UUID_EXPLODED9   0xc0
#define COCLASS_UUID_EXPLODED10  0x19
#define COCLASS_UUID_EXPLODED11  0xa3


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "BON Extender"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "BON Extender Interpreter"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS "MetaGME"


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
