// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "console.h"

/////////////////////////////////////////////////////////////////////////////
// CConsole

IMPLEMENT_DYNCREATE(CConsole, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CConsole properties

CConsole::~CConsole()
{
// commented out by zolmol
//	static BYTE parms[] = VTS_DISPATCH;
//	InvokeHelper(5, DISPATCH_METHOD, VT_EMPTY, NULL, parms, NULL); 
}

CString CConsole::GetContents()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CConsole::SetContents(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

CString CConsole::Get_Contents()
{
	CString result;
	GetProperty(0x0, VT_BSTR, (void*)&result);
	return result;
}

void CConsole::Set_Contents(LPCTSTR propVal)
{
	SetProperty(0x0, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CConsole operations

void CConsole::Message(LPCTSTR str, short type)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 str, type);
}

void CConsole::Clear()
{
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CConsole::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CConsole::SetGMEApp(IDispatch *idp)
{
	static BYTE parms[] = VTS_DISPATCH;
	InvokeHelper(5, DISPATCH_METHOD, VT_EMPTY, NULL, parms, idp);
}

void CConsole::SetGMEProj(IDispatch *idp)
{
	static BYTE parms[] = VTS_DISPATCH;
	InvokeHelper(6, DISPATCH_METHOD, VT_EMPTY, NULL, parms, idp);
}

void CConsole::NavigateTo(LPCTSTR url)
{
	static BYTE parms[] = VTS_BSTR;
	InvokeHelper(7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 url);
}

void CConsole::RunCode(BSTR code)
{
	static BYTE parms[] = VTS_BSTR;
	InvokeHelper(11, DISPATCH_METHOD, VT_EMPTY, NULL, parms, code);
}
