#if !defined(AFX_GMECHILDFRAMEWRAPPER_H__F0C39C74_3223_4146_8CE3_9CEF67CC136A__INCLUDED_)
#define AFX_GMECHILDFRAMEWRAPPER_H__F0C39C74_3223_4146_8CE3_9CEF67CC136A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++


// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CGMEChildFrameWrapper wrapper class

#pragma warning(disable: 4100) // unreferenced formal parameter warning

class CGMEChildFrameWrapper : public CWnd
{
protected:
	DECLARE_DYNCREATE(CGMEChildFrameWrapper)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x1758edff, 0x969c, 0x4f6e, { 0xaf, 0x81, 0xe8, 0xaf, 0x7, 0xa3, 0x37, 0x99 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetCurrentProject(LPUNKNOWN pMgaProject);
	void SetMetaModel(LPUNKNOWN meta);
	void SetModel(LPUNKNOWN model);
	void ChangeAspect(LONG index);
	void CycleAspect(void);
	void Invalidate(void);
	void AboutBox();
};

#pragma warning(default: 4100) // unreferenced formal parameter warning

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GMECHILDFRAMEWRAPPER_H__F0C39C74_3223_4146_8CE3_9CEF67CC136A__INCLUDED_)
