// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "GMEChildFrameWrapper.h"

/////////////////////////////////////////////////////////////////////////////
// CGMEChildFrameWrapper

IMPLEMENT_DYNCREATE(CGMEChildFrameWrapper, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CGMEChildFrameWrapper operations

void CGMEChildFrameWrapper::SetCurrentProject(LPUNKNOWN pMgaProject)
{
	static BYTE parms[] =
		VTS_UNKNOWN;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		pMgaProject);
}

void CGMEChildFrameWrapper::SetMetaModel(LPUNKNOWN meta)
{
	static BYTE parms[] =
		VTS_UNKNOWN;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		meta);
}

void CGMEChildFrameWrapper::SetModel(LPUNKNOWN model)
{
	static BYTE parms[] =
		VTS_UNKNOWN;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		model);
}

void CGMEChildFrameWrapper::ChangeAspect(LONG index)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 index);
}

void CGMEChildFrameWrapper::CycleAspect(void)
{
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CGMEChildFrameWrapper::Invalidate(void)
{
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CGMEChildFrameWrapper::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

