#if !defined(AFX_OBJECTINSPECTOR_H__4139E6B7_A2CD_45F1_9609_45DCA3FDBC51__INCLUDED_)
#define AFX_OBJECTINSPECTOR_H__4139E6B7_A2CD_45F1_9609_45DCA3FDBC51__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CObjectInspector wrapper class

#pragma warning(disable: 4100) // unreferenced formal parameter warning

class CObjectInspector : public CWnd
{
protected:
	DECLARE_DYNCREATE(CObjectInspector)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xb786f53c, 0x297f, 0x4db8, { 0x80, 0x60, 0xd4, 0x50, 0x57, 0x21, 0x7a, 0xee } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	LPUNKNOWN GetMgaProject();
	void SetMgaProject(LPUNKNOWN);
	LPUNKNOWN GetMgaObject();
	void SetMgaObject(LPUNKNOWN);

// Operations
public:
	void ShowPanel(long panelID);
	void EditName();
	void CyclePanel(VARIANT_BOOL frwd);
	void AboutBox();
};

#pragma warning(default: 4100) // unreferenced formal parameter warning

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_OBJECTINSPECTOR_H__4139E6B7_A2CD_45F1_9609_45DCA3FDBC51__INCLUDED_)
