// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "panningwindowwrapper.h"

/////////////////////////////////////////////////////////////////////////////
// CPartBrowser

IMPLEMENT_DYNCREATE(CPanningWindowWrapper, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CPanningWindowWrapper operations

void CPanningWindowWrapper::SetBitmapDC(ULONGLONG ownerWnd, ULONGLONG bDC, ULONGLONG oldBmp,
										LONG orix, LONG oriy, LONG oriw, LONG orih,
										LONG rx, LONG ry, LONG rw, LONG rh,
										OLE_COLOR bkgrnd)
{
	static BYTE parms[] =
		VTS_UI8 VTS_UI8 VTS_UI8 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_COLOR;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		ownerWnd, bDC, oldBmp, orix, oriy, oriw, orih, rx, ry, rw, rh, bkgrnd);
}

void CPanningWindowWrapper::SetViewRect(LONG vrx, LONG vry, LONG vrw, LONG vrh)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		vrx, vry, vrw, vrh);
}

void CPanningWindowWrapper::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
