#if !defined(AFX_PANNINGWINDOWWRAPPER_H__803661F9_1F2F_4592_99AD_85CD4504E4F4__INCLUDED_)
#define AFX_PANNINGWINDOWWRAPPER_H__803661F9_1F2F_4592_99AD_85CD4504E4F4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPanningWindowWrapper wrapper class

#pragma warning(disable: 4100) // unreferenced formal parameter warning

class CPanningWindowWrapper : public CWnd
{
protected:
	DECLARE_DYNCREATE(CPanningWindowWrapper)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xB0C28BAA, 0x7E44, 0x404C, { 0xBE, 0xAD, 0x83, 0x73, 0x53, 0x56, 0xF1, 0xD2 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

	BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetBitmapDC(ULONGLONG ownerWnd, ULONGLONG bDC, ULONGLONG oldBmp,
					 LONG orix, LONG oriy, LONG oriw, LONG orih,
					 LONG rx, LONG ry, LONG rw, LONG rh,
					 OLE_COLOR bkgrnd);
	void SetViewRect(LONG vrx, LONG vry, LONG vrw, LONG vrh);
	void AboutBox();
};

#pragma warning(default: 4100) // unreferenced formal parameter warning

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PANNINGWINDOWWRAPPER_H__803661F9_1F2F_4592_99AD_85CD4504E4F4__INCLUDED_)
