// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "partbrowserwrapper.h"

/////////////////////////////////////////////////////////////////////////////
// CPartBrowserWrapper

IMPLEMENT_DYNCREATE(CPartBrowserWrapper, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CPartBrowserWrapper operations

void CPartBrowserWrapper::SetCurrentProject(LPUNKNOWN pMgaProject)
{
	static BYTE parms[] =
		VTS_UNKNOWN;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		pMgaProject);
}

void CPartBrowserWrapper::SetMetaModel(LPUNKNOWN meta)
{
	static BYTE parms[] =
		VTS_UNKNOWN;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		meta);
}

void CPartBrowserWrapper::SetBgColor(OLE_COLOR oleBgColor)
{
	static BYTE parms[] =
		VTS_COLOR;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		oleBgColor);
}

void CPartBrowserWrapper::ChangeAspect(LONG index)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 index);
}

void CPartBrowserWrapper::CycleAspect(void)
{
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CPartBrowserWrapper::RePaint(void)
{
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CPartBrowserWrapper::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
