#if !defined(AFX_PARTBROWSER_H__A93E5E7F_4E48_44cd_AF65_F45FFECAEBA4__INCLUDED_)
#define AFX_PARTBROWSER_H__A93E5E7F_4E48_44cd_AF65_F45FFECAEBA4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPartBrowserWrapper class

#pragma warning(disable: 4100) // unreferenced formal parameter warning

class CPartBrowserWrapper : public CWnd
{
protected:
	DECLARE_DYNCREATE(CPartBrowserWrapper)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x1FF57057, 0xD598, 0x4FC2, { 0x8F, 0x9D, 0x70, 0x8F, 0x59, 0xB9, 0xC0, 0x17 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetCurrentProject(LPUNKNOWN pMgaProject);
	void SetMetaModel(LPUNKNOWN meta);
	void SetBgColor(OLE_COLOR oleBgColor);
	void ChangeAspect(LONG index);
	void CycleAspect(void);
	void RePaint(void);
	void AboutBox();
};

#pragma warning(default: 4100) // unreferenced formal parameter warning

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PARTBROWSER_H__A93E5E7F_4E48_44cd_AF65_F45FFECAEBA4__INCLUDED_)
