// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "search.h"

/////////////////////////////////////////////////////////////////////////////
// CSearch

IMPLEMENT_DYNCREATE(CSearch, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CSearch properties

LPUNKNOWN CSearch::GetMgaProject()
{
	LPUNKNOWN result;
	GetProperty(0x1, VT_UNKNOWN, (void*)&result);
	return result;
}

void CSearch::SetMgaProject(LPUNKNOWN propVal)
{
	SetProperty(0x1, VT_UNKNOWN, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CSearch operations

void CSearch::OpenProject(LPCTSTR connStr)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 connStr);
}

void CSearch::SelMgaObjects(LPUNKNOWN p_selMgaObjs)
{
	static BYTE parms[] = VTS_UNKNOWN ;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, parms, p_selMgaObjs);
}

void CSearch::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
