#if !defined(AFX_SEARCH_H__70FEF477_CCBA_4AAA_B351_243E241ED5AA__INCLUDED_)
#define AFX_SEARCH_H__70FEF477_CCBA_4AAA_B351_243E241ED5AA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSearch wrapper class

#pragma warning(disable: 4100) // unreferenced formal parameter warning

class CSearch : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSearch)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xe5fe98f1, 0xb7ad, 0x4abe, { 0x89, 0xdb, 0x87, 0xdd, 0xd9, 0xdb, 0x75, 0x3e } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	LPUNKNOWN GetMgaProject();
	void SetMgaProject(LPUNKNOWN);

// Operations
public:
	void OpenProject(LPCTSTR connStr);
	void SelMgaObjects(LPUNKNOWN p_selMgaObjs);
	void AboutBox();
};

#pragma warning(default: 4100) // unreferenced formal parameter warning

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SEARCH_H__70FEF477_CCBA_4AAA_B351_243E241ED5AA__INCLUDED_)
