///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define RAWCOMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "9E10B423-9625-40E4-8956-FC4FCADFAE40"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (JavaCompRunner)"
#define COCLASS_UUID "C97618C3-2574-4257-A6F9-6C3F497DCCED"
#define COCLASS_NAME "MGA Interpreter CoClass (JavaCompRunner)"
#define COCLASS_PROGID "MGA.Interpreter.JavaCompRunner"

#define COCLASS_UUID_EXPLODED1  0xc97618c3
#define COCLASS_UUID_EXPLODED2   0x2574
#define COCLASS_UUID_EXPLODED3   0x4257
#define COCLASS_UUID_EXPLODED4   0xa6
#define COCLASS_UUID_EXPLODED5   0xf9
#define COCLASS_UUID_EXPLODED6   0x6c
#define COCLASS_UUID_EXPLODED7   0x3f
#define COCLASS_UUID_EXPLODED8   0x49
#define COCLASS_UUID_EXPLODED9   0x7d
#define COCLASS_UUID_EXPLODED10  0xcc
#define COCLASS_UUID_EXPLODED11  0xed


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "JavaCompRunner"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "JavaBON Launcher (JavaCompRunner)"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGM_INDEPENDENT

#define GME_BASE ../../../../GME

#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
