// Component configuration file automatically generated as ComponentConfig.h
// by ConfigureComponent on Thu Sep 21 14:32:46 2000


// COM UUID-s, names and progID



// TODO: Modify these macros
// !!! ALWAYS REPLACE THE UUID STRINGS WITH NEW UNIQUE IDS (These new GUIDs can be generated by the guidgen tool)
#define TYPELIB_UUID "268165B3-9D37-4fa3-80BC-CAB25DDBF4BC"
#define TYPELIB_NAME "New Sample Decorator TypeLibrary (Decorator)"
#define COCLASS_UUID "13C74795-8161-4813-B8C6-9D4C3365875C"
#define COCLASS_NAME "New Sample Decorator CoClass (Decorator)"
#define COCLASS_PROGID "MGA.Decorator.NewSampleDecorator"

#define CONSTOLESTR(X)		OLESTR(X)


// This name will appear in the popup window for interpreter selection.
#define DECORATOR_NAME "NewSampleDecorator"

