//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MgaUtil.rc
//
#define IDD_CLOSUREPROPPAGE             107
#define IDD_REGISTRY_BROWSER            169
#define IDC_ZOOMS                       1008
#define IDC_UNDOSIZE                    1009
#define IDC_RADIO1                      1026
#define IDC_DELFILES                    1026
#define IDC_RADIOSYS                    1026
#define IDC_AUTOSAVE_SAME_DIR           1026
#define IDC_WRAPMINIPROJ                1026
#define IDC_NODELFILES                  1027
#define IDC_RADIOUSER                   1027
#define IDC_AUTOSAVE_DEDICATED_DIR      1027
#define IDC_WRAPASIS                    1027
#define IDC_RADIOBOTH                   1028
#define IDC_WRAPAUTO                    1028
#define IDC_ACTIVEDISP                  1029
#define IDC_OUTPUTTOCLIPBOARD           1029
#define IDC_ACTIVE_INACTIVE             1031
#define IDC_OUTPUTTOFILE                1031
#define IDC_ALLCOMPS                    1033
#define IDC_DIRECTIONUP                 1033
#define IDC_DIRECTIONDN                 1034
#define IDC_LIBR1                       1036
#define IDC_LIBR2                       1037
#define IDC_CONNID                      1038
#define IDR_MGAUTIL                     2000
#define IDD_DIALOG_LIST                 2001
#define IDC_LIST                        2002
#define IDR_MGARESOLVER                 2003
#define IDC_CHECK1                      2004
#define IDD_METADLG                     2005
#define IDC_CHECK6                      2005
#define IDR_MGAREGISTRAR                2006
#define IDD_GMEDLG                      2007
#define IDR_MGALAUNCHER                 2008
#define IDD_COMPDLG                     2009
#define IDC_ADDFILE                     2010
#define IDC_MYHELP                      2011
#define IDC_REMOVE                      2013
#define IDC_INFO                        2014
#define IDC_ICONPATH                    2015
#define IDC_ADDICONPATH                 2016
#define IDC_INSTALL                     2017
#define IDR_MGAPROGRESSDLG              2042
#define IDD_PROGRESSDLG                 2043
#define IDD_METAPURGEDIALOG             2044
#define IDI_ICON_REGHERE                2046
#define IDI_ICON_REGMETA                2047
#define IDI_ICON_REGINHERIT             2048
#define IDI_ICON_REGUNDEF               2049
#define IDI_ICON_REGINVALID             2050
#define IDR_CNTXMENU_REGBRW             2051
#define IDB_BITMAP1                     2054
#define IDB_BITMAP2                     2055
#define IDD_COMPINFODLG                 2056
#define IDD_ANNOTATION_BROWSER          2058
#define IDD_XSLTDIAL                    2059
#define IDD_CLOSUREDLG                  2063
#define IDR_MGACLOSURE                  2064
#define IDD_CLOSURERES                  2065
#define IDR_MGAEVENTLOGGER              2066
#define IDD_CLOSURESMARTCP              2067
#define IDD_CLOSUREKINDSEL              2069
#define IDD_CLOSURESIMPLECP             2070
#define IDD_ALTERNMSPDLG                2071
#define IDS_REGISTRAR_NAME              2072
#define IDR_CLR_ASSEMBLY1               2074
#define IDR_COMPONENTPROXY              2090
#define IDC_PROGRESS1                   2150
#define IDC_STATIC1                     2151
#define IDC_STATIC2                     2152
#define IDC_PURGE                       2153
#define IDC_PURGE2                      2155
#define IDC_PURGELIST                   2157
#define IDC_SETCURRENT                  2158
#define IDC_OBJECTNAME                  2160
#define IDC_OBJECTKIND                  2161
#define IDC_OBJECTROLE                  2162
#define IDC_REGISTRY_TREE               2163
#define IDC_REGISTRY_VALUES             2164
#define IDC_REGNODE                     2165
#define IDC_REGNODE_PATH                2166
#define IDC_REGNODE_STATUS              2167
#define IDC_REGNODE_VALUE               2168
#define IDC_STATIC_PATH                 2169
#define IDC_STATIC_STATUS               2170
#define IDC_STATIC_VALUE                2171
#define IDC_SYSICONPATH                 2172
#define IDC_ADDSYSICONPATH              2173
#define IDC_ENABLE_DISABLE              2174
#define IDC_EXT_EDITOR                  2174
#define IDC_EXT_BUTTON                  2175
#define IDC_NAME                        2176
#define IDC_PROGID                      2177
#define IDC_PARADIGM                    2178
#define IDC_DESCRIPTION                 2180
#define IDC_VERSION                     2181
#define IDC_FILENAME                    2182
#define IDC_ENGINECOMBO                 2185
#define IDC_MODELNAME                   2190
#define IDC_MODELKIND                   2191
#define IDC_MODELROLE                   2192
#define IDC_ANNOTATION_LIST             2193
#define IDC_ANNOTATION                  2194
#define IDC_STATIC_NAME                 2195
#define IDC_STATIC_TEXT                 2196
#define IDC_STATIC_COLOR                2197
#define IDC_COMBO_COLOR                 2198
#define IDC_STATIC_BGCOLOR              2199
#define IDC_COMBO_BGCOLOR               2200
#define IDC_STATIC_FONT                 2201
#define IDC_EDIT_FONT                   2202
#define IDC_BUTTON_FONT                 2203
#define IDC_LIST_ASPECT                 2204
#define IDC_STATIC_VISIBILITY           2206
#define IDC_STATIC_XCOORD               2207
#define IDC_EDIT_XCOORD                 2208
#define IDC_STATIC_YCOORD               2209
#define IDC_EDIT_YCOORD                 2210
#define IDC_COMBO_GRADIENTCOLOR         2211
#define IDC_STATIC_SHADOWCOLOR          2212
#define IDC_EDIT_NAME                   2213
#define IDC_EDIT_TEXT                   2214
#define IDC_STATIC_GRADIENTCOLOR        2215
#define IDC_CHECK_DEFPOS                2216
#define IDC_BUTTON1                     2218
#define IDC_BUTTON_IGNORE               2218
#define IDC_AUTOSAVE_DIR_BUTTON         2218
#define IDC_MULTIPLE_OPEN               2219
#define IDC_BUTTON2                     2219
#define IDC_EVENT_LOGGING               2220
#define IDC_EDIT1                       2220
#define IDC_EDIT2                       2221
#define IDC_AUTOSAVE_ENABLED            2221
#define IDC_EDIT3                       2222
#define IDC_AUTOSAVE_FREQ               2222
#define IDC_BUTTON3                     2223
#define IDC_AUTOSAVE_DIR                2223
#define IDC_EXT_ENABLE                  2224
#define IDC_CHECKREFERSTO               2225
#define IDC_CHECKCONNECTION             2226
#define IDC_CHECKSETMEMBER              2227
#define IDC_CHECKCONTAINMENT            2228
#define IDC_CHECKFOLDERCONTAINMENT      2229
#define IDC_DIGINTOLIBRARY              2230
#define IDC_CHECKSUBTYPES               2231
#define IDC_CHECKBASETYPES              2232
#define IDC_BROWSE                      2235
#define IDC_CHECKREFERREDBY             2236
#define IDC_CHECKMEMBEROF               2238
#define IDC_CHECKPARTOFMODEL            2239
#define IDC_CHECKPARTOFFOLDERS          2240
#define IDC_LIST1                       2241
#define IDC_LIBR3                       2242
#define IDC_CHECKSET                    2243
#define IDC_CHECKCONN                   2244
#define IDC_CHECKREF                    2247
#define IDC_INCLUDESOME                 2250
#define IDC_INCLUDEALL                  2251
#define IDC_CHECKREFPORTCONNECTION      2252
#define IDC_CHECK2                      2253
#define IDC_CHECK3                      2254
#define IDC_CHECK4                      2255
#define IDC_CHECK5                      2256
#define IDC_FILTER                      2257
#define IDC_LABELAVOIDANCE              2258
#define IDC_INVERT                      2259
#define IDC_SHOWHIDEBUTTON              2260
#define IDC_REDERIVEBUTTON              2261
#define IDC_EXCONN                      2262
#define IDC_EXREF                       2263
#define IDC_EXATOM                      2264
#define IDC_EXSET                       2265
#define IDC_SENDOVEROBJECT              2266
#define IDC_CMBFMTSTRS                  2268
#define IDC_TIMESTAMPING                2269
#define IDC_EDTPREFIX                   2270
#define IDC_EDTTRUNC                    2271
#define IDC_ALTER_STICKY                2272
#define IDC_APPLY_ALL                   2273
#define IDC_RAD_ALTER0                  2274
#define IDC_RAD_ALTER1                  2275
#define IDC_RAD_ALTER2                  2276
#define IDC_RAD_ALTER3                  2277
#define IDC_CHECKMARK                   2278
#define IDC_EDITMARK                    2279
#define IDC_NAVIGATIONHISTORY           2280
#define IDC_COMBO_SHADOWCOLOR           2281
#define IDC_CHECK_GRADIENTFILL          2282
#define IDC_CHECK_CASTSHADOW            2283
#define IDC_CHECK_ROUNDCORNER           2284
#define IDC_EDIT_SHADOWDEPTH            2285
#define IDC_SPIN2                       2286
#define IDC_EDIT_GRADIENTDIR            2286
#define IDC_STATIC_SHADOWDEPTH          2287
#define IDC_STATIC_GRADIENTDIR          2288
#define IDC_AUTOROUTEDEFAULT            2288
#define IDC_STATIC_CORNERRADIUS         2289
#define IDC_REGISTERSTATIC              2289
#define IDC_EDIT_SHADOWDEPTH3           2290
#define IDC_EDIT_CORNERRADIUS           2290
#define IDC_SHOWCOMPONENTSSTATIC        2290
#define IDC_STATIC_SHADOWDIRECTION      2291
#define IDC_EDGESMOOTHMODE              2291
#define IDC_EDIT_SHADOWDIRECTION        2292
#define IDC_FONTSMOOTHMODE              2292
#define IDC_CHECK_FILES                 2293
#define ID_CNTX_ADDNODE                 32774
#define ID_CNTX_CLEARNODE               32775
#define ID_CNTX_REMOVETREE              32776
#define ID_CNTX_RENAMENODE              32777
#define ID_CNTX_REMOVEALL               32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2075
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         2294
#define _APS_NEXT_SYMED_VALUE           2091
#endif
#endif
