///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define BON2COMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "A80F5574-0EA6-44F4-8001-9B803C3E2960"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (NamespaceConfig)"
#define COCLASS_UUID "7A7B03E5-9132-45EA-919C-C5BEC40387B1"
#define COCLASS_NAME "MGA Interpreter CoClass (NamespaceConfig)"
#define COCLASS_PROGID "MGA.Interpreter.NamespaceConfig"

#define COCLASS_UUID_EXPLODED1  0x7a7b03e5
#define COCLASS_UUID_EXPLODED2   0x9132
#define COCLASS_UUID_EXPLODED3   0x45ea
#define COCLASS_UUID_EXPLODED4   0x91
#define COCLASS_UUID_EXPLODED5   0x9c
#define COCLASS_UUID_EXPLODED6   0xc5
#define COCLASS_UUID_EXPLODED7   0xbe
#define COCLASS_UUID_EXPLODED8   0xc4
#define COCLASS_UUID_EXPLODED9   0x3
#define COCLASS_UUID_EXPLODED10  0x87
#define COCLASS_UUID_EXPLODED11  0xb1


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "NamespaceConfig"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "NamespaceConfig Interpreter"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS "MetaGME"


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
