///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define BON2COMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "55BC0291-4034-4185-8E9D-0909CF06C983"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (BON2SFSample)"
#define COCLASS_UUID "71B6B8C2-00B1-4D23-BE17-D6172C271AA8"
#define COCLASS_NAME "MGA Interpreter CoClass (BON2SFSample)"
#define COCLASS_PROGID "MGA.Interpreter.BON2SFSample"

#define COCLASS_UUID_EXPLODED1  0x71b6b8c2
#define COCLASS_UUID_EXPLODED2   0xb1
#define COCLASS_UUID_EXPLODED3   0x4d23
#define COCLASS_UUID_EXPLODED4   0xbe
#define COCLASS_UUID_EXPLODED5   0x17
#define COCLASS_UUID_EXPLODED6   0xd6
#define COCLASS_UUID_EXPLODED7   0x17
#define COCLASS_UUID_EXPLODED8   0x2c
#define COCLASS_UUID_EXPLODED9   0x27
#define COCLASS_UUID_EXPLODED10  0x1a
#define COCLASS_UUID_EXPLODED11  0xa8


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "BON2SFSample"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "BON2SFSample Interpreter"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS "SF"


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
