///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define BON2COMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "1CB9FEAE-D8F7-48B0-A776-1541149AAF50"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (MetaInterpreter)"
#define COCLASS_UUID "F15CF3E9-7383-44B3-9AB8-A275283BBCA9"
#define COCLASS_NAME "MGA Interpreter CoClass (MetaInterpreter)"
#define COCLASS_PROGID "MGA.Interpreter.MetaInterpreter"

#define COCLASS_UUID_EXPLODED1  0xf15cf3e9
#define COCLASS_UUID_EXPLODED2   0x7383
#define COCLASS_UUID_EXPLODED3   0x44b3
#define COCLASS_UUID_EXPLODED4   0x9a
#define COCLASS_UUID_EXPLODED5   0xb8
#define COCLASS_UUID_EXPLODED6   0xa2
#define COCLASS_UUID_EXPLODED7   0x75
#define COCLASS_UUID_EXPLODED8   0x28
#define COCLASS_UUID_EXPLODED9   0x3b
#define COCLASS_UUID_EXPLODED10  0xbc
#define COCLASS_UUID_EXPLODED11  0xa9


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "MetaInterpreter"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "MetaInterpreter Interpreter"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS "MetaGME"


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
