#ifndef _GMEVIEWDEFS_INCLUDED_
#define _GMEVIEWDEFS_INCLUDED_

#define WM_USER_ZOOM			(WM_USER+111)
#define WM_PANN_SCROLL			(WM_USER+112)
#define WM_USER_PANNREFRESH		(WM_USER+113)


#endif // _GMEVIEWDEFS_INCLUDED_
