// Component configuration file automatically generated as ComponentConfig.h
// by ConfigureComponent on Thu Sep 21 14:32:46 2000


// COM UUID-s, names and progID



// TODO: Modify these macros
// !!! ALWAYS REPLACE THE UUID STRINGS WITH NEW UNIQUE IDS (These new GUIDs can be generated by the guidgen tool)
#define TYPELIB_UUID "[!output TYPELIB_UUID]"
#define TYPELIB_NAME "[!output TYPELIB_NAME]"
#define COCLASS_UUID "[!output COCLASS_UUID]"
#define COCLASS_NAME "[!output COCLASS_NAME]"
#define COCLASS_PROGID "[!output COCLASS_PROGID]"

#define CONSTOLESTR(X)		OLESTR(X)


// This name will appear in the popup window for interpreter selection.
#define DECORATOR_NAME "[!output DECORATOR_NAME]"

