/*
 * Copyright (c) 2002, Vanderbilt University
 * All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement is
 * hereby granted, provided that the above copyright notice, the following
 * two paragraphs and the author appear in all copies of this software.
 * 
 * IN NO EVENT SHALL THE VANDERBILT UNIVERSITY BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE VANDERBILT
 * UNIVERSITY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * THE VANDERBILT UNIVERSITY SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE VANDERBILT UNIVERSITY HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 * Author: Miklos Maroti, Gyorgy Balogh
 * Date last modified: 10/23/03
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_isis_jaut_ComException */

#ifndef _Included_org_isis_jaut_ComException
#define _Included_org_isis_jaut_ComException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_isis_jaut_ComException_serialVersionUID
#define org_isis_jaut_ComException_serialVersionUID -3042686055658047285i64
#undef org_isis_jaut_ComException_serialVersionUID
#define org_isis_jaut_ComException_serialVersionUID -3387516993124229948i64
#undef org_isis_jaut_ComException_serialVersionUID
#define org_isis_jaut_ComException_serialVersionUID -7034897190745766939i64
#undef org_isis_jaut_ComException_S_OK
#define org_isis_jaut_ComException_S_OK 0L
#undef org_isis_jaut_ComException_E_INVALIDARG
#define org_isis_jaut_ComException_E_INVALIDARG -2147024809L
#undef org_isis_jaut_ComException_E_OUTOFMEMORY
#define org_isis_jaut_ComException_E_OUTOFMEMORY -2147024882L
#undef org_isis_jaut_ComException_DISP_E_BADVARTYPE
#define org_isis_jaut_ComException_DISP_E_BADVARTYPE -2147352568L
#undef org_isis_jaut_ComException_DISP_E_OVERFLOW
#define org_isis_jaut_ComException_DISP_E_OVERFLOW -2147352566L
#undef org_isis_jaut_ComException_DISP_E_TYPEMISMATCH
#define org_isis_jaut_ComException_DISP_E_TYPEMISMATCH -2147352571L
#undef org_isis_jaut_ComException_CO_E_NOTINITIALIZED
#define org_isis_jaut_ComException_CO_E_NOTINITIALIZED -2147221008L
/*
 * Class:     org_isis_jaut_ComException
 * Method:    formatMessage
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_isis_jaut_ComException_formatMessage
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
