/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_isis_gme_mga_MgaEventSink */

#ifndef _Included_org_isis_gme_mga_MgaEventSink
#define _Included_org_isis_gme_mga_MgaEventSink
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_isis_gme_mga_MgaEventSink
 * Method:    createSink
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_isis_gme_mga_MgaEventSink_createSink
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
