///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define BON2COMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "34ADD188-D227-43A3-82DD-F920A2081424"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (BON2SFInterpreter)"
#define COCLASS_UUID "257C467E-C7F2-4E70-8B44-817E40C8DE51"
#define COCLASS_NAME "MGA Interpreter CoClass (BON2SFInterpreter)"
#define COCLASS_PROGID "MGA.Interpreter.BON2SFInterpreter"

#define COCLASS_UUID_EXPLODED1  0x257c467e
#define COCLASS_UUID_EXPLODED2   0xc7f2
#define COCLASS_UUID_EXPLODED3   0x4e70
#define COCLASS_UUID_EXPLODED4   0x8b
#define COCLASS_UUID_EXPLODED5   0x44
#define COCLASS_UUID_EXPLODED6   0x81
#define COCLASS_UUID_EXPLODED7   0x7e
#define COCLASS_UUID_EXPLODED8   0x40
#define COCLASS_UUID_EXPLODED9   0xc8
#define COCLASS_UUID_EXPLODED10  0xde
#define COCLASS_UUID_EXPLODED11  0x51


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "BON2SFInterpreter"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "BON2 SignalFlow Interpreter"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS "SF"


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
