//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace MgaMeta
{
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
	public partial class paradigm
	{

		private string commentField;

		private string authorField;

		private string dispnameField;

		private folder folderField;

		private string nameField;

		private string guidField;

		private string versionField;

		private string cdateField;

		private string mdateField;

		/// <remarks/>
		public string comment
		{
			get
			{
				return this.commentField;
			}
			set
			{
				this.commentField = value;
			}
		}

		/// <remarks/>
		public string author
		{
			get
			{
				return this.authorField;
			}
			set
			{
				this.authorField = value;
			}
		}

		/// <remarks/>
		public string dispname
		{
			get
			{
				return this.dispnameField;
			}
			set
			{
				this.dispnameField = value;
			}
		}

		/// <remarks/>
		public folder folder
		{
			get
			{
				return this.folderField;
			}
			set
			{
				this.folderField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string guid
		{
			get
			{
				return this.guidField;
			}
			set
			{
				this.guidField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string version
		{
			get
			{
				return this.versionField;
			}
			set
			{
				this.versionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string cdate
		{
			get
			{
				return this.cdateField;
			}
			set
			{
				this.cdateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string mdate
		{
			get
			{
				return this.mdateField;
			}
			set
			{
				this.mdateField = value;
			}
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class folder {
    
    private string dispnameField;
    
    private object[] itemsField;
    
    private folder[] folder1Field;
    
    private string metarefField;
    
    private string nameField;
    
    private string subfoldersField;
    
    private string rootobjectsField;
    
    /// <remarks/>
    public string dispname {
        get {
            return this.dispnameField;
        }
        set {
            this.dispnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("atom", typeof(atom))]
    [System.Xml.Serialization.XmlElementAttribute("attrdef", typeof(attrdef))]
    [System.Xml.Serialization.XmlElementAttribute("connection", typeof(connection))]
    [System.Xml.Serialization.XmlElementAttribute("constraint", typeof(constraint))]
    [System.Xml.Serialization.XmlElementAttribute("model", typeof(model))]
    [System.Xml.Serialization.XmlElementAttribute("reference", typeof(reference))]
    [System.Xml.Serialization.XmlElementAttribute("regnode", typeof(regnode))]
    [System.Xml.Serialization.XmlElementAttribute("set", typeof(set))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("folder")]
    public folder[] folder1 {
        get {
            return this.folder1Field;
        }
        set {
            this.folder1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string metaref {
        get {
            return this.metarefField;
        }
        set {
            this.metarefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKENS")]
    public string subfolders {
        get {
            return this.subfoldersField;
        }
        set {
            this.subfoldersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKENS")]
    public string rootobjects {
        get {
            return this.rootobjectsField;
        }
        set {
            this.rootobjectsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class atom {
    
    private string dispnameField;
    
    private object[] itemsField;
    
    private string metarefField;
    
    private string nameField;
    
    private string attributesField;
    
    private atomAliasenabled aliasenabledField;
    
    public atom() {
        this.aliasenabledField = atomAliasenabled.no;
    }
    
    /// <remarks/>
    public string dispname {
        get {
            return this.dispnameField;
        }
        set {
            this.dispnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attrdef", typeof(attrdef))]
    [System.Xml.Serialization.XmlElementAttribute("constraint", typeof(constraint))]
    [System.Xml.Serialization.XmlElementAttribute("regnode", typeof(regnode))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string metaref {
        get {
            return this.metarefField;
        }
        set {
            this.metarefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKENS")]
    public string attributes {
        get {
            return this.attributesField;
        }
        set {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(atomAliasenabled.no)]
    public atomAliasenabled aliasenabled {
        get {
            return this.aliasenabledField;
        }
        set {
            this.aliasenabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class attrdef {
    
    private string dispnameField;
    
    private object[] itemsField;
    
    private string metarefField;
    
    private string nameField;
    
    private string viewableField;
    
    private string defvalueField;
    
    private attrdefValuetype valuetypeField;
    
    public attrdef() {
        this.valuetypeField = attrdefValuetype.@string;
    }
    
    /// <remarks/>
    public string dispname {
        get {
            return this.dispnameField;
        }
        set {
            this.dispnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("enumitem", typeof(enumitem))]
    [System.Xml.Serialization.XmlElementAttribute("regnode", typeof(regnode))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string metaref {
        get {
            return this.metarefField;
        }
        set {
            this.metarefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string viewable {
        get {
            return this.viewableField;
        }
        set {
            this.viewableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defvalue {
        get {
            return this.defvalueField;
        }
        set {
            this.defvalueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(attrdefValuetype.@string)]
    public attrdefValuetype valuetype {
        get {
            return this.valuetypeField;
        }
        set {
            this.valuetypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class enumitem {
    
    private string dispnameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dispname {
        get {
            return this.dispnameField;
        }
        set {
            this.dispnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class regnode {
    
    private regnode[] regnode1Field;
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("regnode")]
    public regnode[] regnode1 {
        get {
            return this.regnode1Field;
        }
        set {
            this.regnode1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum attrdefValuetype {
    
    /// <remarks/>
    integer,
    
    /// <remarks/>
    @double,
    
    /// <remarks/>
    boolean,
    
    /// <remarks/>
    @string,
    
    /// <remarks/>
    @enum,
    
    /// <remarks/>
    dynamic,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class constraint {
    
    private string[] itemsField;
    
    private string[] textField;
    
    private string nameField;
    
    private string eventmaskField;
    
    private string priorityField;
    
    private constraintDepth depthField;
    
    private constraintType typeField;
    
    private string defdfornamespField;
    
    public constraint() {
        this.priorityField = "5";
        this.depthField = constraintDepth.Item1;
        this.typeField = constraintType.eventbased;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dispname")]
    public string[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string eventmask {
        get {
            return this.eventmaskField;
        }
        set {
            this.eventmaskField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("5")]
    public string priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(constraintDepth.Item1)]
    public constraintDepth depth {
        get {
            return this.depthField;
        }
        set {
            this.depthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(constraintType.eventbased)]
    public constraintType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defdfornamesp {
        get {
            return this.defdfornamespField;
        }
        set {
            this.defdfornamespField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum constraintDepth {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    any,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum constraintType {
    
    /// <remarks/>
    eventbased,
    
    /// <remarks/>
    ondemand,
    
    /// <remarks/>
    function,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum atomAliasenabled {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class connection {
    
    private string dispnameField;
    
    private object[] itemsField;
    
    private connjoint[] connjointField;
    
    private string metarefField;
    
    private string nameField;
    
    private string attributesField;
    
    private connectionAliasenabled aliasenabledField;
    
    public connection() {
        this.aliasenabledField = connectionAliasenabled.no;
    }
    
    /// <remarks/>
    public string dispname {
        get {
            return this.dispnameField;
        }
        set {
            this.dispnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attrdef", typeof(attrdef))]
    [System.Xml.Serialization.XmlElementAttribute("constraint", typeof(constraint))]
    [System.Xml.Serialization.XmlElementAttribute("regnode", typeof(regnode))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("connjoint")]
    public connjoint[] connjoint {
        get {
            return this.connjointField;
        }
        set {
            this.connjointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string metaref {
        get {
            return this.metarefField;
        }
        set {
            this.metarefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKENS")]
    public string attributes {
        get {
            return this.attributesField;
        }
        set {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(connectionAliasenabled.no)]
    public connectionAliasenabled aliasenabled {
        get {
            return this.aliasenabledField;
        }
        set {
            this.aliasenabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class connjoint {
    
    private pointerspec[] pointerspecField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pointerspec")]
    public pointerspec[] pointerspec {
        get {
            return this.pointerspecField;
        }
        set {
            this.pointerspecField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class pointerspec {
    
    private pointeritem[] pointeritemField;
    
    private string nameField;
    
    private string minField;
    
    private string maxField;
    
    public pointerspec() {
        this.minField = "1";
        this.maxField = "1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pointeritem")]
    public pointeritem[] pointeritem {
        get {
            return this.pointeritemField;
        }
        set {
            this.pointeritemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string min {
        get {
            return this.minField;
        }
        set {
            this.minField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string max {
        get {
            return this.maxField;
        }
        set {
            this.maxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class pointeritem {
    
    private string descField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKENS")]
    public string desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum connectionAliasenabled {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class model {
    
    private string dispnameField;
    
    private object[] itemsField;
    
    private role[] roleField;
    
    private aspect[] aspectField;
    
    private string metarefField;
    
    private string nameField;
    
    private string attributesField;
    
    private modelAliasenabled aliasenabledField;
    
    public model() {
        this.aliasenabledField = modelAliasenabled.no;
    }
    
    /// <remarks/>
    public string dispname {
        get {
            return this.dispnameField;
        }
        set {
            this.dispnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("atom", typeof(atom))]
    [System.Xml.Serialization.XmlElementAttribute("attrdef", typeof(attrdef))]
    [System.Xml.Serialization.XmlElementAttribute("connection", typeof(connection))]
    [System.Xml.Serialization.XmlElementAttribute("constraint", typeof(constraint))]
    [System.Xml.Serialization.XmlElementAttribute("model", typeof(model))]
    [System.Xml.Serialization.XmlElementAttribute("reference", typeof(reference))]
    [System.Xml.Serialization.XmlElementAttribute("regnode", typeof(regnode))]
    [System.Xml.Serialization.XmlElementAttribute("set", typeof(set))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("role")]
    public role[] role {
        get {
            return this.roleField;
        }
        set {
            this.roleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("aspect")]
    public aspect[] aspect {
        get {
            return this.aspectField;
        }
        set {
            this.aspectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string metaref {
        get {
            return this.metarefField;
        }
        set {
            this.metarefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKENS")]
    public string attributes {
        get {
            return this.attributesField;
        }
        set {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(modelAliasenabled.no)]
    public modelAliasenabled aliasenabled {
        get {
            return this.aliasenabledField;
        }
        set {
            this.aliasenabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class reference {
    
    private string dispnameField;
    
    private object[] itemsField;
    
    private pointerspec pointerspecField;
    
    private string metarefField;
    
    private string nameField;
    
    private string attributesField;
    
    private referenceAliasenabled aliasenabledField;
    
    public reference() {
        this.aliasenabledField = referenceAliasenabled.no;
    }
    
    /// <remarks/>
    public string dispname {
        get {
            return this.dispnameField;
        }
        set {
            this.dispnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attrdef", typeof(attrdef))]
    [System.Xml.Serialization.XmlElementAttribute("constraint", typeof(constraint))]
    [System.Xml.Serialization.XmlElementAttribute("regnode", typeof(regnode))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    public pointerspec pointerspec {
        get {
            return this.pointerspecField;
        }
        set {
            this.pointerspecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string metaref {
        get {
            return this.metarefField;
        }
        set {
            this.metarefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKENS")]
    public string attributes {
        get {
            return this.attributesField;
        }
        set {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(referenceAliasenabled.no)]
    public referenceAliasenabled aliasenabled {
        get {
            return this.aliasenabledField;
        }
        set {
            this.aliasenabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum referenceAliasenabled {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class set {
    
    private string dispnameField;
    
    private object[] itemsField;
    
    private pointerspec pointerspecField;
    
    private string metarefField;
    
    private string nameField;
    
    private string attributesField;
    
    private setAliasenabled aliasenabledField;
    
    public set() {
        this.aliasenabledField = setAliasenabled.no;
    }
    
    /// <remarks/>
    public string dispname {
        get {
            return this.dispnameField;
        }
        set {
            this.dispnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attrdef", typeof(attrdef))]
    [System.Xml.Serialization.XmlElementAttribute("constraint", typeof(constraint))]
    [System.Xml.Serialization.XmlElementAttribute("regnode", typeof(regnode))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    public pointerspec pointerspec {
        get {
            return this.pointerspecField;
        }
        set {
            this.pointerspecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string metaref {
        get {
            return this.metarefField;
        }
        set {
            this.metarefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKENS")]
    public string attributes {
        get {
            return this.attributesField;
        }
        set {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(setAliasenabled.no)]
    public setAliasenabled aliasenabled {
        get {
            return this.aliasenabledField;
        }
        set {
            this.aliasenabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum setAliasenabled {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class role {
    
    private string dispnameField;
    
    private regnode[] regnodeField;
    
    private string metarefField;
    
    private string nameField;
    
    private string kindField;
    
    /// <remarks/>
    public string dispname {
        get {
            return this.dispnameField;
        }
        set {
            this.dispnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("regnode")]
    public regnode[] regnode {
        get {
            return this.regnodeField;
        }
        set {
            this.regnodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string metaref {
        get {
            return this.metarefField;
        }
        set {
            this.metarefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string kind {
        get {
            return this.kindField;
        }
        set {
            this.kindField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class aspect {
    
    private string dispnameField;
    
    private regnode[] regnodeField;
    
    private part[] partField;
    
    private string metarefField;
    
    private string nameField;
    
    private string attributesField;
    
    /// <remarks/>
    public string dispname {
        get {
            return this.dispnameField;
        }
        set {
            this.dispnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("regnode")]
    public regnode[] regnode {
        get {
            return this.regnodeField;
        }
        set {
            this.regnodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("part")]
    public part[] part {
        get {
            return this.partField;
        }
        set {
            this.partField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string metaref {
        get {
            return this.metarefField;
        }
        set {
            this.metarefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKENS")]
    public string attributes {
        get {
            return this.attributesField;
        }
        set {
            this.attributesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class part {
    
    private regnode[] regnodeField;
    
    private string metarefField;
    
    private string roleField;
    
    private string kindaspectField;
    
    private partPrimary primaryField;
    
    private bool primaryFieldSpecified;
    
    private partLinked linkedField;
    
    private bool linkedFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("regnode")]
    public regnode[] regnode {
        get {
            return this.regnodeField;
        }
        set {
            this.regnodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string metaref {
        get {
            return this.metarefField;
        }
        set {
            this.metarefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string role {
        get {
            return this.roleField;
        }
        set {
            this.roleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string kindaspect {
        get {
            return this.kindaspectField;
        }
        set {
            this.kindaspectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public partPrimary primary {
        get {
            return this.primaryField;
        }
        set {
            this.primaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool primarySpecified {
        get {
            return this.primaryFieldSpecified;
        }
        set {
            this.primaryFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public partLinked linked {
        get {
            return this.linkedField;
        }
        set {
            this.linkedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool linkedSpecified {
        get {
            return this.linkedFieldSpecified;
        }
        set {
            this.linkedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum partPrimary {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum partLinked {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum modelAliasenabled {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}
