///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define RAWCOMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "E0EDD212-6AEC-41AE-8F45-4A75921D16C7"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (AutoLayout)"
#define COCLASS_UUID "DB312634-F076-4FB2-BCA9-CEF7D239590D"
#define COCLASS_NAME "MGA Interpreter CoClass (AutoLayout)"
#define COCLASS_PROGID "MGA.Interpreter.AutoLayout"

#define COCLASS_UUID_EXPLODED1  0xdb312634
#define COCLASS_UUID_EXPLODED2   0xf076
#define COCLASS_UUID_EXPLODED3   0x4fb2
#define COCLASS_UUID_EXPLODED4   0xbc
#define COCLASS_UUID_EXPLODED5   0xa9
#define COCLASS_UUID_EXPLODED6   0xce
#define COCLASS_UUID_EXPLODED7   0xf7
#define COCLASS_UUID_EXPLODED8   0xd2
#define COCLASS_UUID_EXPLODED9   0x39
#define COCLASS_UUID_EXPLODED10  0x59
#define COCLASS_UUID_EXPLODED11  0xd


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME L"AutoLayout"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT L"Auto Layout PlugIn"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGM_INDEPENDENT


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
