// Component configuration file automatically generated as ComponentConfig.h
// by ConfigureComponent on Thu Sep 21 14:32:46 2000


// COM UUID-s, names and progID



// TODO: Modify these macros
// !!! ALWAYS REPLACE THE UUID STRINGS WITH NEW UNIQUE IDS (These new GUIDs can be generated by the guidgen tool)
#define TYPELIB_UUID "23BBB6E3-540C-460b-9E06-C8708D247A6A"
#define TYPELIB_NAME "MGA Decorator TypeLibrary (Plain Decorator)"
#define COCLASS_UUID "E602520B-12A8-42ad-97D2-561EBACE8142"
#define COCLASS_NAME "MGA Decorator CoClass (Plain Decorator)"
#define COCLASS_PROGID "MGA.Decorator.PlainDecorator"

#define CONSTOLESTR(X)		OLESTR(X)


// This name will appear in the popup window for interpreter selection.
#define DECORATOR_NAME "PlainSampleDecorator"
