///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define BONCOMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "69653354-C8DE-4331-9CF1-F6B73AF6B09D"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (HFSMSimulator)"
#define COCLASS_UUID "3E52908A-15DB-47CC-A569-4F852ED56C5E"
#define COCLASS_NAME "MGA Interpreter CoClass (HFSMSimulator)"
#define COCLASS_PROGID "MGA.Interpreter.HFSMSimulator"

#define COCLASS_UUID_EXPLODED1  0x3e52908a
#define COCLASS_UUID_EXPLODED2   0x15db
#define COCLASS_UUID_EXPLODED3   0x47cc
#define COCLASS_UUID_EXPLODED4   0xa5
#define COCLASS_UUID_EXPLODED5   0x69
#define COCLASS_UUID_EXPLODED6   0x4f
#define COCLASS_UUID_EXPLODED7   0x85
#define COCLASS_UUID_EXPLODED8   0x2e
#define COCLASS_UUID_EXPLODED9   0xd5
#define COCLASS_UUID_EXPLODED10  0x6c
#define COCLASS_UUID_EXPLODED11  0x5e


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "HFSMSimulator"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "HFSM Simulator"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS "HFSM"


#define BON_ICON_SUPPORT

#define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
